development: &development
  adapter: postgresql
  encoding: utf8
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"
  port: 5432
  database: post_anonymously_system_development
  username: postgres
  password: 24373514
  pool: 5

test:
  <<: *development
  database: book_storm_new_test

production:
  <<: *development
  database: post_anonymously_system_development_production
  username: postgres
  password: 24373514
  pool: 25